[package]
authors = ["Apollo Developers <opensource@apollographql.com>"]
edition = "2018"
name = "rover"
version = "0.0.0"

[dependencies]

# workspace deps
houston = { path = "./crates/houston" }
rover-client = { path = "./crates/rover-client" }
sputnik = { path = "./crates/sputnik" }
timber = { path = "./crates/timber" }

# crates.io deps
anyhow = "1.0.31"
console = "0.12.0"
serde = "1.0"
serde_json = "1.0"
structopt = "0.3.15"
url = "2.1.1"
tracing = "0.1.21"

[dev-dependencies]
assert_cmd = "1.0.1"
assert_fs = "1.0.0"
serial_test = "0.5.0"
predicates = "1.0.5"

[workspace]
members = [".", "crates/*"]

