[build]
  base    = "docs/"
  publish = "public/"
  ignore  = false
  command = "gatsby build --prefix-paths && mkdir -p docs/rover && mv public/* docs/rover && mv docs public/ && mv public/docs/rover/_redirects public"
